/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, BigNumber, BigNumberish, BaseContract, ContractTransaction, Overrides, CallOverrides } from 'ethers'
import { Provider } from '@ethersproject/providers'

export class Buyer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  buyAndBurn(amount: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  info(overrides?: CallOverrides): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      balance: BigNumber
      autoBurnedBnb: BigNumber
      autoBurnedFdao: BigNumber
      manualBurnedBnb: BigNumber
      manualBurnedFdao: BigNumber
    }
  >

  initialize(_fdao: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>
}
