/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, BigNumber, BaseContract, ContractTransaction, Overrides, CallOverrides } from 'ethers'
import { Provider } from '@ethersproject/providers'

export class Inviters extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  initialize(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  invited(arg0: string, overrides?: CallOverrides): Promise<BigNumber>

  inviters(arg0: string, overrides?: CallOverrides): Promise<string>

  setInviter(inviter: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>
}
