/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, BigNumber, BigNumberish, BaseContract, ContractTransaction, Overrides, CallOverrides } from 'ethers'
import { Provider } from '@ethersproject/providers'

export class Lucky extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  active(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  harvest(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  initialize(
    _fdao: string,
    _pool: string,
    _rank: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  join(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  status(
    user: string,
    overrides?: CallOverrides
  ): Promise<
    [
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        lastDay: BigNumber
        income: BigNumber
        dividends: BigNumber
        bonus: BigNumber
        totalDividends: BigNumber
        totalBonus: BigNumber
        totalPay: BigNumber
      },
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      info: [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        lastDay: BigNumber
        income: BigNumber
        dividends: BigNumber
        bonus: BigNumber
        totalDividends: BigNumber
        totalBonus: BigNumber
        totalPay: BigNumber
      }
      invited: BigNumber
      burned: BigNumber
      balance: BigNumber
    }
  >
}
